vars: {
  d2-config: {
    theme-id: 3 # terrastruct
    sketch: true
  }
  colors: {
    c2: "#C7F1FF" # açık turkuaz
    c3: "#B5AFF6" # koyu mor
    c4: "#DEE1EB" # gri
    c5: "#88DCF7" # turkuaz
    c6: "#E4DBFE" # mor
  }
}

UI: User Interface {
  link: fe.svg
  tooltip: React with Hilla components, Tailwind, Reactflow.
  Pages
  Components
  Models: {
    style: {
      fill: ${colors.c3}
      stroke-dash: 10
      stroke-width: 1
      stroke: black
    }
  }
}
UI <- App: Hilla pushes contracts {
  style.animated: true
  style.stroke: ${colors.c3}
  style.font-size: 20
}

# APP
App: "Application" {
  Repositories

  Services
  Models: {
    Developer
    Skill
    Project
    style.fill: ${colors.c3}
  }
  ModuleService: {
    ModuleHost: {
      style.stroke-dash: 10
      style.stroke: black
      style.fill: ${colors.c2}
    }
  }
}
App -> Core: {
  style.animated: true
}

"""
MongoDB: "🍃 MongoDB" {
  shape: cylinder
  style.fill: "#13aa52"
  style.stroke: black
  style.font-color: white
  near:Core.Domain
}
MongoDB <- App.Repositories: {
  direction:left
}
"""

# CORE
Core: {
  Domain
  Module System: {
    Context
    ModuleHost: {
      style.fill: ${colors.c2}
    }
  }
  Modules: {
    shape: queue
    Scrum: {
      style.fill: ${colors.c5}
    }
    Kanban: {
      style.fill: ${colors.c5}
    }
    DORA: {
      style.fill: ${colors.c5}
    }
    Drive: {
      style.fill: ${colors.c5}
    }
    "...": {
      style.fill: ${colors.c5}
      style.animated: true
      tooltip: Main Extensibility Point — Expecting the community to add modules for management theories.
      style.stroke: red
      style.multiple: true
    }
    style.fill: ${colors.c2}
  }
  AI Module Connector: {
    style.fill: ${colors.c5}
    style.stroke: red
  }
  AI Module Connector -> Modules
  Module System.ModuleHost -> Modules
}
